<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>ShinraRotationPatch</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\src\RotationEnricher.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DamageMeter">
      <HintPath>..\work\DamageMeter.p1.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Data">
      <HintPath>..\libs\Data.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Tera.Core">
      <HintPath>..\libs\Tera.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
