<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Patcher</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\src\Patcher.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>

</Project>
